const productos= [
    {id: 1, producto: "Adidas Gazelle Unisex", marca:"ADIDAS", precio: 4000},
    {id: 2, producto: "Adidas Gazelle Unisex", marca:"ADIDAS", precio: 4000},
    {id: 3, producto: "Adidas Gazelle Unisex", marca:"ADIDAS", precio: 4000},
    {id: 4, producto: "Adidas Gazelle Unisex", marca:"ADIDAS", precio: 4000},
    {id: 5, producto: "Adidas Gazelle Unisex", marca:"ADIDAS", precio: 4000},
    {id: 6, producto: "Adidas Gazelle Unisex", marca:"ADIDAS", precio: 4000},
    {id: 7, producto: "Fila Disruptor", marca: "FILA", precio: 2500},
    {id: 8, producto: "Fila Disruptor", marca: "FILA", precio: 2500},
    {id: 9, producto: "Fila Disruptor", marca: "FILA", precio: 2500},
    {id: 10, producto: "Fila Disruptor", marca: "FILA", precio: 2500},
    {id: 11, producto: "Fila Disruptor", marca: "FILA", precio: 2500},
    {id: 12, producto: "Fila Disruptor", marca: "FILA", precio: 2500},
    {id: 13, producto: "Converse All Star Blue", marca:"CONVERSE", precio: 2800},
    {id: 14, producto: "Converse All Star Blue", marca:"CONVERSE", precio: 2800},
    {id: 15, producto: "Converse All Star Blue", marca:"CONVERSE", precio: 2800},
    {id: 16, producto: "Converse All Star Blue", marca:"CONVERSE", precio: 2800},
    {id: 17, producto: "Converse All Star Blue", marca:"CONVERSE", precio: 2800},
    {id: 18, producto: "Converse All Star Blue", marca:"CONVERSE", precio: 2800},
    {id: 19, producto: "New Balance 530 Pink", marca: "NEW BALANCE", precio: 4850},
    {id: 20, producto: "New Balance 530 Pink", marca: "NEW BALANCE", precio: 4850},
    {id: 21, producto: "New Balance 530 Pink", marca: "NEW BALANCE", precio: 4850},
    {id: 22, producto: "New Balance 530 Pink", marca: "NEW BALANCE", precio: 4850},
    {id: 23, producto: "New Balance 530 Pink", marca: "NEW BALANCE", precio: 4850},
    {id: 24, producto: "New Balance 530 Pink", marca: "NEW BALANCE", precio: 4850},
    {id: 25, producto: "Air Jordan High 1 Panda", marca: "NIKE", precio: 4400},
    {id: 26, producto: "Air Jordan High 1 Panda", marca: "NIKE", precio: 4400},
    {id: 27, producto: "Air Jordan High 1 Panda", marca: "NIKE", precio: 4400},
    {id: 28, producto: "Air Jordan High 1 Panda", marca: "NIKE", precio: 4400},
    {id: 29, producto: "Air Jordan High 1 Panda", marca: "NIKE", precio: 4400},
    {id: 30, producto: "Air Jordan High 1 Panda", marca: "NIKE", precio: 4400},
    {id: 31, producto: "Classic Puma Pink", marca: "PUMA", precio: 3500},
    {id: 32, producto: "Classic Puma Pink", marca: "PUMA", precio: 3500},
    {id: 33, producto: "Classic Puma Pink", marca: "PUMA", precio: 3500},
    {id: 34, producto: "Classic Puma Pink", marca: "PUMA", precio: 3500},
    {id: 35, producto: "Classic Puma Pink", marca: "PUMA", precio: 3500},
    {id: 36, producto: "Classic Puma Pink", marca: "PUMA", precio: 3500}
];  