const products= [
    {id: 1, image: "../assets/Adidas_gazelle.jpg", productName: "Adidas Gazelle Unisex", marca:"ADIDAS", price: 4000},
    {id: 2, image: "../assets/AdidasZX700.jpg", productName: "Adidas Gazelle Unisex", marca:"ADIDAS", price: 4000},
    {id: 3, image: "../assets/adidaszx750.jpg", productName: "Adidas Gazelle Unisex", marca:"ADIDAS", price: 4000},
    {id: 4, image: "../assets/AdidasSuperstar.jpg", productName: "Adidas Gazelle Unisex", marca:"ADIDAS", price: 4000},
    {id: 5, image: "../assets/AdidasRivalry.jpg", productName: "Adidas Gazelle Unisex", marca:"ADIDAS", price: 4000},
    {id: 6, image: "../assets/adidasY-3.jpg", productName: "Adidas Gazelle Unisex", marca:"ADIDAS", price: 4000},
    {id: 7, image: "../assets/fila_distruptor.jpg", productName: "Fila Disruptor", marca: "FILA", price: 2500},
    {id: 8, image: "../assets/fila_distruptorxAtipici.jpg", productName: "Fila Disruptor", marca: "FILA", price: 2500},
    {id: 9, image: "../assets/FilaFastCharge.jpg", productName: "Fila Disruptor", marca: "FILA", price: 2500},
    {id: 10, image: "../assets/FilaCheckerboardFaux.jpg", productName: "Fila Disruptor", marca: "FILA", price: 2500},
    {id: 11, image: "../assets/FilaDIstruptor2premium.jpg", productName: "Fila Disruptor", marca: "FILA", price: 2500},
    {id: 12, image: "../assets/FilaMultiTrigate.jpg", productName: "Fila Disruptor", marca: "FILA", price: 2500},
    {id: 13, image: "../assets/ConverseChuckTaylor.jpg", productName: "Converse All Star Blue", marca:"CONVERSE", price: 2800},
    {id: 14, image: "../assets/OffspringConverseChuck70.jpg", productName: "Converse All Star Blue", marca:"CONVERSE", price: 2800},
    {id: 15, image: "../assets/ConverseCanvasWedgeHighTop.jpg", productName: "Converse All Star Blue", marca:"CONVERSE", price: 2800},
    {id: 16, image: "../assets/ConverseAll-StarBlue.jpg", productName: "Converse All Star Blue", marca:"CONVERSE", price: 2800},
    {id: 17, image: "../assets/ConversStarPlayer.jpg", productName: "Converse All Star Blue", marca:"CONVERSE", price: 2800},
    {id: 18, image: "../assets/ConverseStarPlayerBlue.jpg", productName: "Converse All Star Blue", marca:"CONVERSE", price: 2800},
    {id: 19, image: "../assets/New_balance_574_grey.jpg", productName: "New Balance 530 Pink", marca: "NEW BALANCE", price: 4850},
    {id: 20, image: "../assets/NewBalance997H.jpg", productName: "New Balance 530 Pink", marca: "NEW BALANCE", price: 4850},
    {id: 21, image: "../assets/NewBalance574Aplinepack.jpg", productName: "New Balance 530 Pink", marca: "NEW BALANCE", price: 4850},
    {id: 22, image: "../assets/NewBalance574Beige.jpg", productName: "New Balance 530 Pink", marca: "NEW BALANCE", price: 4850},
    {id: 23, image: "../assets/NewBalanceFuelcell.jpg", productName: "New Balance 530 Pink", marca: "NEW BALANCE", price: 4850},
    {id: 24, image: "../assets/NewBalance530.jpg", productName: "New Balance 530 Pink", marca: "NEW BALANCE", price: 4850},
    {id: 25, image: "../assets/AirJordan1.jpg", productName: "Air Jordan High 1 Panda", marca: "NIKE", price: 4400},
    {id: 26, image: "../assets/airJordanRetro.jpg", productName: "Air Jordan High 1 Panda", marca: "NIKE", price: 4400},
    {id: 27, image: "../assets/NikeAirForce1spiderman.jpg", productName: "Air Jordan High 1 Panda", marca: "NIKE", price: 4400},
    {id: 28, image: "../assets/NikePinkwhite.jpg", productName: "Air Jordan High 1 Panda", marca: "NIKE", price: 4400},
    {id: 29, image: "../assets/NikeClassicCortez.jpg", productName: "Air Jordan High 1 Panda", marca: "NIKE", price: 4400},
    {id: 30, image: "../assets/NikeLeopard.jpg", productName: "Air Jordan High 1 Panda", marca: "NIKE", price: 4400},
    {id: 31, image: "../assets/ClassicPumasneakers.jpg", productName: "Classic Puma Pink", marca: "PUMA", price: 3500},
    {id: 32, image: "../assets/PumaCaliSport.jpg", productName: "Classic Puma Pink", marca: "PUMA", price: 3500},
    {id: 33, image: "../assets/PumaCaliStarMix.jpg", productName: "Classic Puma Pink", marca: "PUMA", price: 3500},
    {id: 34, image: "../assets/PumaBasketPlatform.jpg", productName: "Classic Puma Pink", marca: "PUMA", price: 3500},
    {id: 35, image: "../assets/PumaCaliBold.jpg",productName: "Classic Puma Pink", marca: "PUMA", price: 3500},
    {id: 36, image: "../assets/PumaRalphSampson.jpg",productName: "Classic Puma Pink", marca: "PUMA", price: 3500}
];  